path: "/Dev/cicd"
host: "localhost"
port: "9092"
mule.version: "4.2.1"
username: "OnPrem02Student10"
password: "L3arnmule"
cloudhub.application.name: "LocalcicdApp"
environment: "Sandbox"
anypoint.businessGroup: "OnPrem02Group10"